[project]
name = "dot-agent"
version = "0.1.0"
description = "CLI tool for managing .agent/ automated documentation folders"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.1.7",
    "pyyaml>=6.0.0",
]

[project.scripts]
dot-agent = "dot_agent.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/dot_agent"]

[tool.hatch.build.targets.wheel.force-include]
"src/dot_agent/resources" = "dot_agent/resources"
