[project]
name = "mdstack-dev"
version = "0.1.0"
description = "Development tools for managing dot-agent kits"
requires-python = ">=3.13"
dependencies = [
    "click>=8.1.7",
]

[project.scripts]
mdstack-dev = "mdstack_dev.__main__:cli"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/mdstack_dev"]
