[project]
name = "dev-runners-da-kit"
version = "0.1.0"
description = "Development runner agents for Claude Code (pytest, ruff, pyright, prettier)"
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "Workstack Team"}
]
keywords = ["claude-code", "dot-agent", "pytest", "ruff", "pyright", "prettier"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

[project.urls]
Homepage = "https://github.com/workstack/workstack"
Repository = "https://github.com/workstack/workstack"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = []

[tool.hatch.build.targets.wheel.force-include]
"kit.yaml" = "kit.yaml"
"agents" = "agents"
