"""Re-export from erk_shared for backward compatibility."""

from erk_shared.github.metadata_blocks import (
    PLAN_METADATA_MARKER_END,
    PLAN_METADATA_MARKER_START,
    ImplementationStatusSchema,
    MetadataBlock,
    MetadataBlockSchema,
    PlanIssueSchema,
    PlanSchema,
    ProgressStatusSchema,
    RawMetadataBlock,
    WorktreeCreationSchema,
    create_implementation_status_block,
    create_metadata_block,
    create_plan_block,
    create_plan_issue_block,
    create_progress_status_block,
    create_worktree_creation_block,
    extract_metadata_value,
    extract_raw_metadata_blocks,
    find_metadata_block,
    parse_metadata_block_body,
    parse_metadata_blocks,
    render_erk_issue_event,
    render_metadata_block,
)

__all__ = [
    "ImplementationStatusSchema",
    "MetadataBlock",
    "MetadataBlockSchema",
    "PLAN_METADATA_MARKER_END",
    "PLAN_METADATA_MARKER_START",
    "PlanIssueSchema",
    "PlanSchema",
    "ProgressStatusSchema",
    "RawMetadataBlock",
    "WorktreeCreationSchema",
    "create_implementation_status_block",
    "create_metadata_block",
    "create_plan_block",
    "create_plan_issue_block",
    "create_progress_status_block",
    "create_worktree_creation_block",
    "extract_metadata_value",
    "extract_raw_metadata_blocks",
    "find_metadata_block",
    "parse_metadata_block_body",
    "parse_metadata_blocks",
    "render_erk_issue_event",
    "render_metadata_block",
]
