name: "Check Submission Folder"
description: "Check if .submission/ directory exists"
outputs:
  has_submission:
    description: "Whether .submission/ directory exists (true/false)"
    value: ${{ steps.check.outputs.has_submission }}
runs:
  using: "composite"
  steps:
    - name: Check for .submission/ directory
      id: check
      shell: bash
      run: |
        if test -d .submission/; then
          echo "has_submission=true" >> $GITHUB_OUTPUT
        else
          echo "has_submission=false" >> $GITHUB_OUTPUT
        fi
